#! python

import numpy as np
import matplotlib.pyplot as plt

# Constants
g = 9.81  # Acceleration due to gravity (m/s^2)

# Drone parameters
mass = 1.5  # Mass of the drone (kg)
rotor_area = 0.1  # Rotor area (m^2)
air_density = 1.225  # Air density at sea level (kg/m^3)
C_L = 1.0  # Lift coefficient (assumed constant for simplicity)
C_D = 0.1  # Drag coefficient (assumed constant for simplicity)

# Functions to calculate forces


def calculate_lift(thrust):
    """Calculate lift force based on thrust."""
    return thrust


def calculate_weight(mass):
    """Calculate weight of the drone."""
    return mass * g


def calculate_drag(velocity):
    """Calculate drag force based on velocity."""
    return C_D * 0.5 * air_density * rotor_area * velocity**2


# Simulation parameters
time_step = 0.1  # Time step for simulation (s)
total_time = 20.0  # Total time for simulation (s)
num_steps = int(total_time / time_step)

# Initialize arrays to store results
time_array = np.linspace(0, total_time, num_steps)
altitude_array = np.zeros(num_steps)
velocity_array = np.zeros(num_steps)

# Initial conditions
thrust = 15.0  # Thrust generated by the rotors (N)
altitude = 0.0  # Initial altitude (m)
velocity = 0.0  # Initial velocity (m/s)

# Simulation loop
for i in range(1, num_steps):
    lift = calculate_lift(thrust)
    weight = calculate_weight(mass)

    if lift > weight:
        # Ascending
        net_force = lift - weight - calculate_drag(velocity)
        acceleration = net_force / mass
    elif lift < weight:
        # Descending
        net_force = -weight + lift - calculate_drag(velocity)
        acceleration = net_force / mass
    else:
        # Hovering
        acceleration = 0

    # Update velocity and altitude
    velocity += acceleration * time_step
    altitude += velocity * time_step

    # Store results
    velocity_array[i] = velocity
    altitude_array[i] = altitude

# Plotting results
plt.figure(figsize=(12, 6))
plt.subplot(2, 1, 1)
plt.plot(time_array, altitude_array, label='Altitude (m)', color='blue')
plt.title('Drone Flight Simulation')
plt.xlabel('Time (s)')
plt.ylabel('Altitude (m)')
plt.grid()
plt.legend()

plt.subplot(2, 1, 2)
plt.plot(time_array, velocity_array, label='Velocity (m/s)', color='red')
plt.xlabel('Time (s)')
plt.ylabel('Velocity (m/s)')
plt.grid()
plt.legend()

plt.tight_layout()
plt.show()
